sifo_admin_homepage:
    pattern:  /administrator
    defaults: { _controller: SifoAdminBundle:Default:index }

logout:
    pattern:  /admlogout
    defaults: { _controller: SifoAdminBundle:Default:adminlogout }
    
sifo_admin_signup:
    pattern:  /signup
    defaults: { _controller: SifoAdminBundle:Default:signup }

admin_home:
    pattern: /home
    defaults: { _controller: SifoAdminBundle:Default:adminhome }
    
admin_dataguru:
    pattern: /dataguru
    defaults: { _controller: SifoAdminBundle:Default:dataguru }
    
admin_datasiswa:
    pattern: /datasiswa
    defaults: { _controller: SifoAdminBundle:Default:datasiswa }
    
admin_datakelas:
    pattern: /datakelas
    defaults: { _controller: SifoAdminBundle:Default:datakelas }

admin_dataadmin:
    pattern: /dataadmin
    defaults: { _controller: SifoAdminBundle:Default:dataadmin }
    
delete_dataadmin:
    pattern: /adelete/{id}
    defaults : { _controller: SifoAdminBundle:Admin:deleteadmin }
    
admin_databerita:
    pattern: /databerita
    defaults: { _controller: SifoAdminBundle:Default:databerita }
    
delete_berita:
    pattern: /deleteberita/{id}
    defaults: { _controller: SifoAdminBundle:Default:deleteberita }
    
edit_datakelas:
    pattern: /datakelas/{id}
    defaults: { _controller: SifoAdminBundle:Admin:editkelas }
    
edit_dataguru:
    pattern: /dataguru/{id}
    defaults : { _controller: SifoAdminBundle:Admin:editguru }
    
delete_dataguru:
    pattern: /gdelete/{id}
    defaults : { _controller: SifoAdminBundle:Admin:deleteguru }
    
edit_datasiswa:
    pattern: /datasiswa/{id}
    defaults : { _controller: SifoAdminBundle:Admin:editsiswa }
    
delete_datasiswa:
    pattern: /sdelete/{id}
    defaults : { _controller: SifoAdminBundle:Admin:deletesiswa }
    
